name: Commit Validation
on:
  push:
    branches:
      - main
  schedule:
    - cron: "55 23 * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2

      - uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.10"

      - run: python fuzz.py
      shell: bash
